spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: off

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ec2-15-165-119-94.ap-northeast-2.compute.amazonaws.com:3306/local?serverTimezone=UTC
    username: root
    password: secret

  config:
    import:
      - classpath:client.yml
server:
  port: 8080
